### ISSUE TITLE
a bug in a new version of ordered_set

### ISSUE THREAD

**Issue by lotus-devo** [LuminosoInsight/ordered-set#69]
I run a pylatex program on ubuntu on Ubuntu 16.04 with Python 3.5. I got following error:
Traceback (most recent call last):
  File "test1.py", line 2, in <module>
    import pylatex as pl
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/__init__.py", line 8, in <module>
    from .basic import HugeText, NewPage, LineBreak, NewLine, HFill, LargeText, \
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/basic.py", line 9, in <module>
    from .base_classes import CommandBase, Environment, ContainerCommand
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/base_classes/__init__.py", line 8, in <module>
    from .latex_object import LatexObject
  File "/home/dongl/.local/lib/python3.5/site-packages/pylatex/base_classes/latex_object.py", line 9, in <module>
    from ordered_set import OrderedSet
  File "/home/dongl/.local/lib/python3.5/site-packages/ordered_set.py", line 51, in <module>
    class OrderedSet(MutableSet[T], Sequence[T]):
  File "/home/dongl/.local/lib/python3.5/site-packages/ordered_set.py", line 186, in OrderedSet
    def update(self, sequence: SetLike[T]) -> int:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

Siunds like a bug in view version of ordered_set, how can I solve this?

**Comment by rspeer** [comment]
Hi, sorry about that -- this is the same as #67, where I accidentally broke Python 3.5 support by using new features of the typing module. The fix was still a pull request. I've now merged it and released version 4.0.2.
