### ISSUE TITLE
It should be possible to build ordered-set without setuptools installed

### ISSUE THREAD

**Issue by jachymb** [LuminosoInsight/ordered-set#76]
python setuptools attempt to import ordered_set. Therefore it should be possible to build ordered_set with setuptools uninstalled. Perhaps try something like this:

    try:
        from setuptools import setup
    except ImportError:
        from distutils.core import setup

**Comment by rspeer** [comment]
Sorry, can you clarify? setuptools itself is depending on ordered-set?

Though it's hard to find clarity on exactly what a setup.py "should" contain, I believed I was following best practices here. And [PEP 632](https://www.python.org/dev/peps/pep-0632/) tells me that importing distutils is going to be deprecated in 8 months.

**Comment by rspeer** [comment]
I took a look at setuptools to find that, in fact, the `sdist` command uses ordered-set. That's neat!

It also looks like setuptools has some machinery for including vendored dependencies that are copied into the setuptools directory, which seems like entirely the right way to do things so that not everything is a circular dependency.

Part of my motivation to keep ordered-set as a single Python module -- aside from just avoiding scope creep -- is that it can be very easily vendored into projects that can't use pip for whatever reason.

Is there some reason that this vendoring process isn't working in this case?

**Comment by amirtal-cp** [comment]
without setuptools:
```
❯ python3 -m pip install --upgrade ordered-set
Requirement already satisfied: ordered-set in /usr/local/lib/python3.9/site-packages (3.1)
Collecting ordered-set
  Using cached ordered-set-4.0.2.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0bec6915cb80478790fd0dcbf8a11a41/setup.py'"'"'; __file__='"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0bec6915cb80478790fd0dcbf8a11a41/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-pip-egg-info-tyobwwh0
         cwd: /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0bec6915cb80478790fd0dcbf8a11a41/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/usr/local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/usr/local/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f5/ab/8252360bfe965bba31ec05112b3067bd129ce4800d89e0b85613bc6044f6/ordered-set-4.0.2.tar.gz#sha256=ba93b2df055bca202116ec44b9bead3df33ea63a7d5827ff8e16738b97f33a95 (from https://pypi.org/simple/ordered-set/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached ordered-set-4.0.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_d42f18c5cac948d9b4d217345499d0df/setup.py'"'"'; __file__='"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_d42f18c5cac948d9b4d217345499d0df/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-pip-egg-info-z80mqe5s
         cwd: /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_d42f18c5cac948d9b4d217345499d0df/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/usr/local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/usr/local/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/89/5d/60db38c980730fc91a0a9cf4c2b932037eecfbd6926aa2ebf450247c0096/ordered-set-4.0.1.tar.gz#sha256=a31008c57f9c9776b12eb8841b1f61d1e4d70dfbbe8875ccfa2403c54af3d51b (from https://pypi.org/simple/ordered-set/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached ordered-set-3.1.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0fdbfb032fb941698e9861274b68c590/setup.py'"'"'; __file__='"'"'/private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0fdbfb032fb941698e9861274b68c590/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-pip-egg-info-1m4boz71
         cwd: /private/var/folders/jz/gh2db8td29q2prqyhbzsbf3h7xy09n/T/pip-install-783vx4j3/ordered-set_0fdbfb032fb941698e9861274b68c590/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools.depends import Require
      File "/usr/local/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/usr/local/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a3/b7/d4d69641cbe707a45c23b190f2d717466ba5accc4c70b5f7a8a450387895/ordered-set-3.1.1.tar.gz#sha256=a7bfa858748c73b096e43db14eb23e2bc714a503f990c89fac8fab9b0ee79724 (from https://pypi.org/simple/ordered-set/) (requires-python:>=2.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

after:
```
❯ python3 -m pip install --upgrade setuptools
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (41.0.1)
Collecting setuptools
  Downloading setuptools-57.0.0-py3-none-any.whl (821 kB)
     |████████████████████████████████| 821 kB 921 kB/s
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 41.0.1
    Uninstalling setuptools-41.0.1:
      Successfully uninstalled setuptools-41.0.1
Successfully installed setuptools-57.0.0

❯ python3 -m pip install --upgrade ordered-set
Requirement already satisfied: ordered-set in /usr/local/lib/python3.9/site-packages (3.1)
Collecting ordered-set
  Using cached ordered-set-4.0.2.tar.gz (10 kB)
Building wheels for collected packages: ordered-set
  Building wheel for ordered-set (setup.py) ... done
  Created wheel for ordered-set: filename=ordered_set-4.0.2-py2.py3-none-any.whl size=8218 sha256=a1160e44068792d94ef529858c4dfefa582b3f86b7b05352b5d2d7f8432f753c
  Stored in directory: /Users/amirtal/Library/Caches/pip/wheels/c0/a1/09/0c736ab4beb6a48ae2f5f2529b2ad3770c8e6cc32d01d75a2c
Successfully built ordered-set
Installing collected packages: ordered-set
  Attempting uninstall: ordered-set
    Found existing installation: ordered-set 3.1
    Uninstalling ordered-set-3.1:
      Successfully uninstalled ordered-set-3.1
Successfully installed ordered-set-4.0.2
```

**Comment by rspeer** [comment]
Taking a look at this again.

I don't understand why the "without setuptools" version has files such as `/usr/local/lib/python3.9/site-packages/setuptools/py33compat.py`, indicating that setuptools is installed. Could this be a conflict involving multiple Python installations? It doesn't look to me like it's connected to anything in ordered-set.

**Comment by amirtal-cp** [comment]
cannot re-produce when using stock python image (python:3.9.7).
so it might be related to conflicting python versions.

```
❯ docker run -it python:3.9.7 /bin/bash
Unable to find image 'python:3.9.7' locally
3.9.7: Pulling from library/python
955615a668ce: Pull complete
2756ef5f69a5: Pull complete
911ea9f2bd51: Pull complete
27b0a22ee906: Pull complete
8584d51a9262: Pull complete
524774b7d363: Pull complete
af193b9b3d11: Pull complete
aacb0e56e8f3: Pull complete
46cd7abc9e93: Pull complete
Digest: sha256:e6654afa815122b13242fc9ff513e2d14b00548ba6eaf4d3b03f2f261d85272d
Status: Downloaded newer image for python:3.9.7
root@f801b7daa5dc:/#
root@f801b7daa5dc:/#
root@f801b7daa5dc:/#
root@f801b7daa5dc:/# python3 -m pip install --upgrade ordered-set
Collecting ordered-set
  Downloading ordered-set-4.0.2.tar.gz (10 kB)
Building wheels for collected packages: ordered-set
  Building wheel for ordered-set (setup.py) ... done
  Created wheel for ordered-set: filename=ordered_set-4.0.2-py2.py3-none-any.whl size=8219 sha256=70658ce1746193908d1daf80404078c92eedd04ad413e76bd943463eec4b30ad
  Stored in directory: /root/.cache/pip/wheels/c0/a1/09/0c736ab4beb6a48ae2f5f2529b2ad3770c8e6cc32d01d75a2c
Successfully built ordered-set
Installing collected packages: ordered-set
Successfully installed ordered-set-4.0.2
root@f801b7daa5dc:/#
```

**Comment by rspeer** [comment]
I'm looking into using Poetry as the primary way of building ordered-set, which would solve this problem.
